import { useState } from 'react';
import { Pressable, TextInput, View } from 'react-native';
import { Card, Screen, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import type { NativeAuthController } from '@mobile/auth/session';

export type AuthScreenMode = 'login' | 'signup' | 'reset' | 'update-password';
export function AuthScreen({ mode, controller, resetRedirectTo, onAuthenticated, onNavigate }: { mode: AuthScreenMode; controller: NativeAuthController; resetRedirectTo: string; onAuthenticated: (destination: 'today' | 'onboarding') => void; onNavigate: (mode: AuthScreenMode) => void }) {
  const { theme } = useSarthiTheme(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const styles = { shell: { flex: 1, justifyContent: 'center' as const, padding: theme.spacing.shell }, card: { gap: theme.spacing.md }, input: { borderColor: theme.colors.line, borderRadius: theme.radius.input, borderWidth: theme.border.hairline, color: theme.colors.ink1, minHeight: theme.layout.hitTarget, paddingHorizontal: theme.spacing.md, ...theme.typography.body }, links: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.md }, link: { minHeight: theme.layout.hitTarget, justifyContent: 'center' as const } };
  const submit = async () => { setMessage(null); if (mode === 'update-password' && password !== confirm) { setMessage('Passwords do not match.'); return; } setBusy(true); try { if (mode === 'login') { const session = await controller.signIn({ email, password }); onAuthenticated(session.onboardingComplete ? 'today' : 'onboarding'); } else if (mode === 'signup') { await controller.signUp({ email, password }); onAuthenticated('onboarding'); } else if (mode === 'reset') { await controller.requestPasswordReset(email, resetRedirectTo); setMessage('If this address is eligible, a reset link has been sent.'); } else { await controller.updatePassword(password); onNavigate('login'); } } catch { setMessage('Something went wrong. Your details are still here, so you can try again.'); } finally { setBusy(false); } };
  const title = mode === 'signup' ? 'Create account' : mode === 'login' ? 'Welcome back' : mode === 'reset' ? 'Reset password' : 'Set a new password';
  return <Screen><View style={styles.shell}><Card style={styles.card}><SarthiText role="display">{title}</SarthiText>{mode !== 'update-password' && <TextInput accessibilityLabel="Email" autoCapitalize="none" autoComplete="email" keyboardType="email-address" value={email} onChangeText={setEmail} style={styles.input} />}{mode !== 'reset' && <TextInput accessibilityLabel="Password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} secureTextEntry value={password} onChangeText={setPassword} style={styles.input} />}{mode === 'update-password' && <TextInput accessibilityLabel="Confirm password" autoComplete="new-password" secureTextEntry value={confirm} onChangeText={setConfirm} style={styles.input} />}{message && <SarthiText role="caption" tone="secondary">{message}</SarthiText>}<SarthiButton label={busy ? 'Working' : mode === 'login' ? 'Sign in' : mode === 'signup' ? 'Create account' : mode === 'reset' ? 'Send reset link' : 'Save password'} disabled={busy} onPress={() => void submit()} />{mode === 'login' && <View style={styles.links}><Pressable accessibilityRole="button" onPress={() => onNavigate('signup')} style={styles.link}><SarthiText role="caption" tone="secondary">Create an account</SarthiText></Pressable><Pressable accessibilityRole="button" onPress={() => onNavigate('reset')} style={styles.link}><SarthiText role="caption" tone="secondary">Forgot password</SarthiText></Pressable></View>}{mode === 'signup' && <Pressable accessibilityRole="button" onPress={() => onNavigate('login')} style={styles.link}><SarthiText role="caption" tone="secondary">I have an account</SarthiText></Pressable>}</Card></View></Screen>;
}
