import { Pressable, ScrollView, View } from 'react-native';
import { Card, Screen, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import type { HabitLensModel } from './types';

export function HabitsLens({ model, onToggle, onStack }: { model: HabitLensModel; onToggle?: (id: string) => void; onStack?: () => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme);
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><SarthiText role="caption" tone="habits">HABITS</SarthiText><SarthiText role="displayXl">{model.headline}</SarthiText><SarthiText role="coach" tone="secondary">{model.coachRead}</SarthiText></View><View style={styles.group}><SarthiText role="caption" tone="muted">CHECKLIST</SarthiText>{model.habits.map((habit) => <Pressable key={habit.id} accessibilityRole="checkbox" accessibilityState={{ checked: habit.status !== 'pending', disabled: habit.status === 'satisfied' }} disabled={habit.status === 'satisfied'} onPress={() => onToggle?.(habit.id)} style={styles.habit}><View style={styles.copy}><SarthiText role="body">{habit.title}</SarthiText><SarthiText role="caption" tone="muted">{habit.streakLabel}{habit.detail ? ` · ${habit.detail}` : ''}</SarthiText></View><SarthiText role="caption" tone={habit.status === 'satisfied' ? 'health' : 'habits'}>{habit.status === 'done' ? 'Done' : habit.status === 'satisfied' ? 'Auto' : 'Mark done'}</SarthiText></Pressable>)}</View><View style={styles.group}><SarthiText role="caption" tone="muted">MONTH</SarthiText><View accessibilityLabel="Monthly habit completion grid" style={styles.heatmap}>{model.month.map((day) => <View key={day.id} accessibilityLabel={day.label} style={[styles.day, { backgroundColor: day.complete ? theme.colors.habits : theme.colors.raised }]} />)}</View></View>{model.stackSuggestion && <Card><SarthiText role="body">{model.stackSuggestion}</SarthiText><Pressable accessibilityRole="button" onPress={onStack} style={styles.stackAction}><SarthiText role="caption" tone="habits">Stack it</SarthiText></Pressable></Card>}</ScrollView></Screen>;
}
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { content: { gap: theme.spacing.lg, padding: theme.spacing.shell, paddingBottom: theme.spacing.xxl }, heading: { gap: theme.spacing.xs }, group: { gap: theme.spacing.xs }, habit: { alignItems: 'center' as const, backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: theme.radius.input, borderWidth: theme.border.hairline, flexDirection: 'row' as const, gap: theme.spacing.sm, minHeight: theme.layout.hitTarget, justifyContent: 'space-between' as const, padding: theme.spacing.md }, copy: { flex: 1, gap: theme.spacing.xxs }, heatmap: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.xs }, day: { borderRadius: theme.radius.chip, height: theme.spacing.md, width: theme.spacing.md }, stackAction: { alignSelf: 'flex-start' as const, minHeight: theme.layout.hitTarget, justifyContent: 'center' as const } }; }
