import { Pressable, ScrollView, View } from 'react-native';
import { Card, Screen, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import type { HealthLensModel, LensEntry } from './types';

export function HealthLens({ model, onMetricPress, onEntryPress }: { model: HealthLensModel; onMetricPress?: (id: string) => void; onEntryPress?: (id: string) => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme);
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><SarthiText role="caption" tone="health">HEALTH</SarthiText><SarthiText role="displayXl">{model.headline}</SarthiText><SarthiText role="coach" tone="secondary">{model.coachRead}</SarthiText></View><View style={styles.metrics}>{model.metrics.map((metric) => <Pressable key={metric.id} accessibilityRole="button" onPress={() => onMetricPress?.(metric.id)} style={styles.metric}><SarthiText role="caption" tone="health">{metric.label}</SarthiText><SarthiText role="display">{metric.valueLabel}</SarthiText></Pressable>)}</View><LensSection label="MEALS" entries={model.meals} onEntryPress={onEntryPress} />{model.workout && <LensSection label="WORKOUT" entries={[model.workout]} onEntryPress={onEntryPress} />}{model.weight && <LensSection label="WEIGHT" entries={[model.weight]} onEntryPress={onEntryPress} />}</ScrollView></Screen>;
}
function LensSection({ label, entries, onEntryPress }: { label: string; entries: LensEntry[]; onEntryPress?: (id: string) => void }) { const { theme } = useSarthiTheme(); const styles = makeStyles(theme); return <View style={styles.group}><SarthiText role="caption" tone="muted">{label}</SarthiText>{entries.map((entry) => <Pressable key={entry.id} accessibilityRole="button" onPress={() => onEntryPress?.(entry.id)} style={styles.entry}><View style={styles.entryCopy}><SarthiText role="body">{entry.title}</SarthiText><SarthiText role="caption" tone="muted">{entry.detail}{entry.estimated ? ' · estimate' : ''}</SarthiText></View><SarthiText role="body">{entry.valueLabel}</SarthiText></Pressable>)}</View>; }
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { content: { gap: theme.spacing.lg, padding: theme.spacing.shell, paddingBottom: theme.spacing.xxl }, heading: { gap: theme.spacing.xs }, metrics: { flexDirection: 'row' as const, gap: theme.spacing.xs }, metric: { backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: theme.radius.card, borderWidth: theme.border.hairline, flex: 1, gap: theme.spacing.xxs, minHeight: theme.layout.hitTarget, padding: theme.spacing.sm }, group: { gap: theme.spacing.xs }, entry: { alignItems: 'center' as const, flexDirection: 'row' as const, gap: theme.spacing.sm, minHeight: theme.layout.hitTarget, justifyContent: 'space-between' as const }, entryCopy: { flex: 1, gap: theme.spacing.xxs } }; }
