import { Pressable, ScrollView, View } from 'react-native';
import { Card, Screen, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import type { MoneyLensModel } from './types';

export function MoneyLens({ model, onEntryPress, onBudgetPress }: { model: MoneyLensModel; onEntryPress?: (id: string) => void; onBudgetPress?: (id: string) => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme);
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.heading}><SarthiText role="caption" tone="money">MONEY</SarthiText><SarthiText role="displayXl">{model.balanceLabel}</SarthiText><SarthiText role="body">Safe to spend: {model.safeToSpendLabel}</SarthiText><SarthiText role="coach" tone="secondary">{model.coachRead}</SarthiText></View><View style={styles.group}><SarthiText role="caption" tone="muted">BUDGETS</SarthiText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.shelf}>{model.budgets.map((budget) => <Pressable key={budget.id} accessibilityRole="button" onPress={() => onBudgetPress?.(budget.id)} style={styles.budget}><SarthiText role="body">{budget.label}</SarthiText><SarthiText role="caption" tone="muted">{budget.valueLabel}</SarthiText></Pressable>)}</ScrollView></View>{model.recurring.length > 0 && <View style={styles.group}><SarthiText role="caption" tone="muted">RECURRING</SarthiText><View style={styles.recurring}>{model.recurring.map((entry) => <View key={entry} style={styles.recurringChip}><SarthiText role="caption">{entry}</SarthiText></View>)}</View></View>}{model.leak && <Card><SarthiText role="body">{model.leak}</SarthiText></Card>}<View style={styles.group}><SarthiText role="caption" tone="muted">LEDGER</SarthiText>{model.entries.map((entry) => <Pressable key={entry.id} accessibilityRole="button" onPress={() => onEntryPress?.(entry.id)} style={styles.entry}><View style={styles.entryCopy}><SarthiText role="body">{entry.title}</SarthiText><SarthiText role="caption" tone="muted">{entry.detail}{entry.estimated ? ' · estimate' : ''}</SarthiText></View><SarthiText role="body">{entry.valueLabel}</SarthiText></Pressable>)}</View></ScrollView></Screen>;
}
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { content: { gap: theme.spacing.lg, padding: theme.spacing.shell, paddingBottom: theme.spacing.xxl }, heading: { gap: theme.spacing.xs }, group: { gap: theme.spacing.xs }, shelf: { gap: theme.spacing.xs }, budget: { backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: theme.radius.card, borderWidth: theme.border.hairline, gap: theme.spacing.xxs, minHeight: theme.layout.hitTarget, padding: theme.spacing.md }, recurring: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.xs }, recurringChip: { backgroundColor: theme.colors.raised, borderRadius: theme.radius.chip, paddingHorizontal: theme.spacing.md, paddingVertical: theme.spacing.xs }, entry: { alignItems: 'center' as const, flexDirection: 'row' as const, gap: theme.spacing.sm, minHeight: theme.layout.hitTarget, justifyContent: 'space-between' as const }, entryCopy: { flex: 1, gap: theme.spacing.xxs } }; }
