import { Pressable, ScrollView, View } from 'react-native';
import { Card, Screen, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import type { SkillLensModel } from './types';

export function SkillsLens({ model, onSkillPress, onMilestoneToggle, onStartFocus }: { model: SkillLensModel; onSkillPress?: (id: string) => void; onMilestoneToggle?: (skillId: string, milestoneId: string) => void; onStartFocus?: (skillId: string) => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme);
  if (model.tracks.length === 0) return <Screen><Card style={styles.empty}><SarthiText role="display">Name anything.</SarthiText><SarthiText role="body" tone="secondary">I will build the road.</SarthiText></Card></Screen>;
  return <Screen><ScrollView contentContainerStyle={styles.content}><SarthiText role="caption" tone="skills">SKILLS</SarthiText>{model.tracks.map((track) => <Card key={track.id} style={styles.track}><Pressable accessibilityRole="button" onPress={() => onSkillPress?.(track.id)} style={styles.trackHeading}><SarthiText role="display">{track.title}</SarthiText><SarthiText role="code" tone="secondary">{track.hoursLabel} · {track.levelLabel}</SarthiText><SarthiText role="caption" tone="secondary">{track.next}</SarthiText></Pressable><View style={styles.milestones}>{track.milestones.map((milestone) => <Pressable key={milestone.id} accessibilityRole="checkbox" accessibilityState={{ checked: milestone.done }} onPress={() => onMilestoneToggle?.(track.id, milestone.id)} style={styles.milestone}><SarthiText role="caption" tone={milestone.done ? 'skills' : 'secondary'}>{milestone.done ? 'Complete' : milestone.suggested ? 'Next' : 'Later'} · {milestone.title}</SarthiText></Pressable>)}</View><View style={styles.sessions}>{track.sessions.map((session) => <View key={session.id} style={styles.session}><SarthiText role="caption">{session.title}</SarthiText><SarthiText role="code" tone="muted">{session.valueLabel}</SarthiText></View>)}</View><SarthiButton label="Start focus" onPress={() => onStartFocus?.(track.id)} /></Card>)}</ScrollView></Screen>;
}
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { content: { gap: theme.spacing.md, padding: theme.spacing.shell, paddingBottom: theme.spacing.xxl }, empty: { gap: theme.spacing.xs, margin: theme.spacing.shell, marginTop: theme.spacing.xxl }, track: { gap: theme.spacing.md }, trackHeading: { gap: theme.spacing.xxs }, milestones: { gap: theme.spacing.xxs }, milestone: { minHeight: theme.layout.hitTarget, justifyContent: 'center' as const }, sessions: { gap: theme.spacing.xxs }, session: { flexDirection: 'row' as const, justifyContent: 'space-between' as const } }; }
