import { useState } from 'react';
import { Pressable, ScrollView, TextInput, View } from 'react-native';
import { Card, Screen, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';

export type CoachReading = { id: string; scope: 'daily' | 'weekly' | 'answer'; dateLabel: string; body: string; evidenceLabel?: string; adaptation?: { id: string; label: string } };
export function CoachReadingRoom({ today, weekly, history, onAsk, onAdaptationPress }: { today: CoachReading; weekly?: CoachReading; history: CoachReading[]; onAsk: (question: string) => void | Promise<void>; onAdaptationPress?: (id: string) => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme); const [question, setQuestion] = useState(''); const [historyOpen, setHistoryOpen] = useState(false); const submit = () => { const value = question.trim(); if (!value) return; setQuestion(''); void onAsk(value); };
  return <Screen><View style={styles.screen}><ScrollView contentContainerStyle={styles.content}><SarthiText role="display">Coach</SarthiText><Reading reading={today} onAdaptationPress={onAdaptationPress} />{weekly && <Card><SarthiText role="caption" tone="muted">THIS WEEK</SarthiText><Reading reading={weekly} onAdaptationPress={onAdaptationPress} /></Card>}{history.length > 0 && <View style={styles.history}><Pressable accessibilityRole="button" onPress={() => setHistoryOpen((open) => !open)} style={styles.historyHeader}><SarthiText role="caption" tone="muted">EARLIER</SarthiText><SarthiText role="caption" tone="muted">{historyOpen ? 'Hide' : 'Show'}</SarthiText></Pressable>{historyOpen && history.map((reading) => <Reading key={reading.id} reading={reading} onAdaptationPress={onAdaptationPress} />)}</View>}</ScrollView><View style={styles.ask}><TextInput accessibilityLabel="Ask your coach" placeholder="Ask your coach" placeholderTextColor={theme.colors.ink3} value={question} onChangeText={setQuestion} onSubmitEditing={submit} style={styles.input} /><SarthiButton label="Ask" onPress={submit} /></View></View></Screen>;
}
function Reading({ reading, onAdaptationPress }: { reading: CoachReading; onAdaptationPress?: (id: string) => void }) { const { theme } = useSarthiTheme(); const styles = makeStyles(theme); return <View style={styles.reading}><SarthiText role="caption" tone="muted">{reading.scope === 'weekly' ? 'WEEKLY' : reading.dateLabel}</SarthiText><SarthiText role="coach">{reading.body}</SarthiText>{reading.evidenceLabel && <SarthiText role="caption" tone="muted">{reading.evidenceLabel}</SarthiText>}{reading.adaptation && <Pressable accessibilityRole="button" onPress={() => onAdaptationPress?.(reading.adaptation!.id)} style={styles.adaptation}><SarthiText role="caption">{reading.adaptation.label}</SarthiText></Pressable>}</View>; }
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { screen: { flex: 1 }, content: { gap: theme.spacing.lg, padding: theme.spacing.shell, paddingBottom: theme.spacing.md }, reading: { gap: theme.spacing.xxs }, history: { gap: theme.spacing.xs }, historyHeader: { alignItems: 'center' as const, flexDirection: 'row' as const, justifyContent: 'space-between' as const, minHeight: theme.layout.hitTarget }, adaptation: { alignSelf: 'flex-start' as const, minHeight: theme.layout.hitTarget, justifyContent: 'center' as const }, ask: { alignItems: 'center' as const, backgroundColor: theme.colors.raised, flexDirection: 'row' as const, gap: theme.spacing.xs, padding: theme.spacing.xs }, input: { color: theme.colors.ink1, flex: 1, minHeight: theme.layout.hitTarget, ...theme.typography.body } }; }
