import { Pressable, ScrollView, View } from 'react-native';
import { Card, Screen, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';

export type JourneyEvent = { id: string; kind: 'memory'; dateLabel: string; title: string; caption: string; domain: string; imageLabel?: string; entryId?: string } | { id: string; kind: 'milestone'; dateLabel: string; title: string; detail: string };
export function JourneyTimeline({ events, onMemoryPress, onMilestonePress, onStartCapture }: { events: JourneyEvent[]; onMemoryPress?: (entryId: string) => void; onMilestonePress?: (id: string) => void; onStartCapture?: () => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme);
  if (events.length === 0) return <Screen><Card style={styles.empty}><SarthiText role="display">Keep the proof.</SarthiText><SarthiText role="body" tone="secondary">Snap your first meal, receipt, or workout.</SarthiText><SarthiButton label="Open capture" onPress={onStartCapture} /></Card></Screen>;
  return <Screen><ScrollView contentContainerStyle={styles.content}><SarthiText role="display">Journey</SarthiText><View style={styles.rail}>{events.map((event) => <View key={event.id} style={styles.event}><View style={[styles.node, { backgroundColor: event.kind === 'milestone' ? theme.colors.energy : theme.colors.ink3 }]} /><View style={styles.eventBody}>{event.kind === 'memory' ? <Pressable accessibilityRole="button" onPress={() => event.entryId && onMemoryPress?.(event.entryId)}><Card style={styles.memory}><SarthiText role="caption" tone="muted">{event.dateLabel} · {event.domain}</SarthiText><SarthiText role="title">{event.title}</SarthiText><SarthiText role="body" tone="secondary">{event.caption}</SarthiText>{event.imageLabel && <SarthiText role="caption" tone="muted">{event.imageLabel}</SarthiText>}</Card></Pressable> : <Pressable accessibilityRole="button" onPress={() => onMilestonePress?.(event.id)} style={styles.milestone}><SarthiText role="caption" tone="muted">MILESTONE · {event.dateLabel}</SarthiText><SarthiText role="title">{event.title}</SarthiText><SarthiText role="caption" tone="secondary">{event.detail}</SarthiText></Pressable>}</View></View>)}</View></ScrollView></Screen>;
}
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { content: { gap: theme.spacing.md, padding: theme.spacing.shell, paddingBottom: theme.spacing.xxl }, empty: { gap: theme.spacing.sm, margin: theme.spacing.shell, marginTop: theme.spacing.xxl }, rail: { gap: theme.spacing.md }, event: { flexDirection: 'row' as const, gap: theme.spacing.sm }, node: { borderRadius: theme.radius.chip, height: theme.spacing.sm, marginTop: theme.spacing.sm, width: theme.spacing.sm }, eventBody: { flex: 1 }, memory: { gap: theme.spacing.xxs }, milestone: { gap: theme.spacing.xxs, minHeight: theme.layout.hitTarget, justifyContent: 'center' as const } }; }
