import { useState } from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import { Card, Screen, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';

export type StatsMode = 'current' | 'potential' | 'day-one';
export type StatCard = { id: string; label: string; headline: string; detail: string; levelLabel: string; dimmed?: boolean };
export type StatsModel = { overall: StatCard; domains: StatCard[]; potentialUnavailable?: boolean };
export function StatsWall({ models, onDomainPress }: { models: Record<StatsMode, StatsModel>; onDomainPress?: (id: string) => void }) {
  const { theme } = useSarthiTheme(); const styles = makeStyles(theme); const [mode, setMode] = useState<StatsMode>('current'); const model = models[mode];
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><SarthiText role="display">Stats</SarthiText><View style={styles.toggle}>{(['current', 'potential', 'day-one'] as StatsMode[]).map((entry) => <Pressable key={entry} accessibilityRole="tab" accessibilityState={{ selected: mode === entry }} onPress={() => setMode(entry)} style={[styles.tab, { backgroundColor: mode === entry ? theme.colors.raised : theme.colors.card }]}><SarthiText role="caption">{entry === 'day-one' ? 'Day 1' : entry}</SarthiText></Pressable>)}</View></View><Card style={styles.overall}><SarthiText role="caption" tone="muted">OVERALL</SarthiText><SarthiText role="displayXl">{model.overall.headline}</SarthiText><SarthiText role="body">{model.overall.detail}</SarthiText><SarthiText role="caption" tone="muted">{model.overall.levelLabel}</SarthiText></Card>{mode === 'potential' && model.potentialUnavailable && <SarthiText role="caption" tone="muted">Come back in a few days. I need more real data.</SarthiText>}<View style={styles.grid}>{model.domains.map((card) => <Pressable key={card.id} accessibilityRole="button" onPress={() => onDomainPress?.(card.id)} style={styles.card}><SarthiText role="caption" tone="muted">{card.label}</SarthiText><SarthiText role="display">{card.headline}</SarthiText><SarthiText role="caption" tone="secondary">{card.detail}</SarthiText><SarthiText role="caption">{card.levelLabel}</SarthiText></Pressable>)}</View></ScrollView></Screen>;
}
function makeStyles(theme: ReturnType<typeof useSarthiTheme>['theme']) { return { content: { gap: theme.spacing.md, padding: theme.spacing.shell, paddingBottom: theme.spacing.xxl }, top: { gap: theme.spacing.xs }, toggle: { flexDirection: 'row' as const, gap: theme.spacing.xxs }, tab: { borderRadius: theme.radius.chip, justifyContent: 'center' as const, minHeight: theme.layout.hitTarget, paddingHorizontal: theme.spacing.sm }, overall: { gap: theme.spacing.xxs }, grid: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.xs }, card: { backgroundColor: theme.colors.card, borderColor: theme.colors.line, borderRadius: theme.radius.card, borderWidth: theme.border.hairline, gap: theme.spacing.xxs, minHeight: theme.layout.hitTarget, padding: theme.spacing.md, width: '47%' as const } }; }
