import { useState } from 'react';
import { Pressable, View } from 'react-native';
import { Card, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import { formatTimer, type TimerStore, useDurableTimer } from './timer';

export type FocusPreset = { label: string; minutes: number };
export function FocusTimer({ store, skillId, presets, onComplete, onAbandon }: { store: TimerStore; skillId: string; presets: FocusPreset[]; onComplete: (input: { skillId: string; minutes: number }) => void | Promise<void>; onAbandon: (input: { skillId: string; minutes: number; choice: 'log' | 'discard' }) => void | Promise<void> }) {
  const { theme } = useSarthiTheme(); const [abandonedMinutes, setAbandonedMinutes] = useState<number | null>(null); const timer = useDurableTimer({ kind: 'focus', store, onElapsed: async (record) => { await onComplete({ skillId: record.contextId ?? skillId, minutes: Math.floor(record.durationSeconds / 60) }); } });
  const styles = { card: { gap: theme.spacing.md }, presets: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.xs }, preset: { backgroundColor: theme.colors.raised, borderRadius: theme.radius.chip, justifyContent: 'center' as const, minHeight: theme.layout.hitTarget, paddingHorizontal: theme.spacing.md }, timer: { alignSelf: 'center' as const, color: theme.colors.skills, ...theme.typography.displayXl }, actions: { flexDirection: 'row' as const, gap: theme.spacing.xs } };
  if (abandonedMinutes !== null) return <Card style={styles.card}><SarthiText role="title">Log {abandonedMinutes} minutes?</SarthiText><SarthiText role="body" tone="secondary">Only measured time can be filed.</SarthiText><View style={styles.actions}><SarthiButton label="Discard" onPress={() => { void onAbandon({ skillId, minutes: abandonedMinutes, choice: 'discard' }); setAbandonedMinutes(null); }} /><SarthiButton label="Log time" onPress={() => { void onAbandon({ skillId, minutes: abandonedMinutes, choice: 'log' }); setAbandonedMinutes(null); }} /></View></Card>;
  return <Card style={styles.card}><SarthiText role="title" tone="skills">Focus</SarthiText>{timer.record ? <><SarthiText role="displayXl" style={styles.timer}>{formatTimer(timer.remainingSeconds)}</SarthiText><SarthiButton label="End session" onPress={() => { void timer.stop().then((ended) => { if (ended) setAbandonedMinutes(ended.elapsedMinutes); }); }} /></> : <><SarthiText role="body" tone="secondary">Choose a session for this skill.</SarthiText><View style={styles.presets}>{presets.map((preset) => <Pressable key={preset.label} accessibilityRole="button" onPress={() => void timer.start(preset.minutes * 60, skillId)} style={styles.preset}><SarthiText role="caption">{preset.label}</SarthiText></Pressable>)}</View></>}</Card>;
}
