import { Pressable, View } from 'react-native';
import { Card, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import { formatTimer, type TimerStore, useDurableTimer } from './timer';

export type BreathPattern = { id: string; label: string; minutes: number; phases: readonly string[] };
export function MeditationTimer({ store, patterns, onComplete }: { store: TimerStore; patterns: BreathPattern[]; onComplete: (input: { minutes: number }) => void | Promise<void> }) {
  const { theme } = useSarthiTheme(); const timer = useDurableTimer({ kind: 'meditation', store, onElapsed: async (record) => { await onComplete({ minutes: Math.floor(record.durationSeconds / 60) }); } }); const active = patterns.find((pattern) => pattern.id === timer.record?.contextId); const styles = { card: { gap: theme.spacing.md }, choices: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.xs }, choice: { backgroundColor: theme.colors.raised, borderRadius: theme.radius.chip, justifyContent: 'center' as const, minHeight: theme.layout.hitTarget, paddingHorizontal: theme.spacing.md }, breath: { alignItems: 'center' as const, backgroundColor: theme.colors.habits, borderRadius: theme.radius.chip, height: theme.layout.captureTarget, justifyContent: 'center' as const, width: theme.layout.captureTarget }, running: { alignItems: 'center' as const, gap: theme.spacing.sm } };
  return <Card style={styles.card}><SarthiText role="title" tone="habits">Meditation</SarthiText>{timer.record && active ? <View style={styles.running}><View accessibilityLabel="Breathing exercise active" style={styles.breath}><SarthiText role="caption">Breathe</SarthiText></View><SarthiText role="display">{formatTimer(timer.remainingSeconds)}</SarthiText><SarthiText role="coach" tone="secondary">{active.phases[0]}</SarthiText><SarthiButton label="End meditation" onPress={() => { void timer.stop(); }} /></View> : <><SarthiText role="body" tone="secondary">Choose a quiet pattern.</SarthiText><View style={styles.choices}>{patterns.map((pattern) => <Pressable key={pattern.id} accessibilityRole="button" onPress={() => void timer.start(pattern.minutes * 60, pattern.id)} style={styles.choice}><SarthiText role="caption">{pattern.label}</SarthiText></Pressable>)}</View></>}</Card>;
}
