import { useEffect, useState } from 'react';
import { Pressable, TextInput, View } from 'react-native';
import { Card, Screen, SarthiButton, SarthiText } from '@mobile/components/primitives';
import { useSarthiTheme } from '@mobile/theme';
import { isQuestionAnswered, updateAnswer, type OnboardingDraft, type OnboardingDraftStore, type OnboardingQuestion } from './model';

export function OnboardingFlow({ questions, store, onComplete, onSignIn }: { questions: OnboardingQuestion[]; store: OnboardingDraftStore; onComplete: (draft: OnboardingDraft) => void | Promise<void>; onSignIn?: () => void }) {
  const { theme } = useSarthiTheme(); const [draft, setDraft] = useState<OnboardingDraft>({ stepId: questions[0]?.id ?? '', answers: {}, selectedDomains: [] }); const currentIndex = Math.max(0, questions.findIndex((question) => question.id === draft.stepId)); const question = questions[currentIndex]; const styles = { screen: { flex: 1, justifyContent: 'center' as const, padding: theme.spacing.shell }, card: { gap: theme.spacing.md }, options: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.xs }, option: { backgroundColor: theme.colors.raised, borderRadius: theme.radius.chip, minHeight: theme.layout.hitTarget, justifyContent: 'center' as const, paddingHorizontal: theme.spacing.md }, input: { borderColor: theme.colors.line, borderRadius: theme.radius.input, borderWidth: theme.border.hairline, color: theme.colors.ink1, minHeight: theme.layout.hitTarget, paddingHorizontal: theme.spacing.md, ...theme.typography.body }, actions: { flexDirection: 'row' as const, gap: theme.spacing.xs, justifyContent: 'space-between' as const } };
  useEffect(() => { void store.load().then((saved) => { if (saved) setDraft(saved); }); }, [store]);
  if (!question) return <Screen><View style={styles.screen}><Card><SarthiText role="display">One sentence a day.</SarthiText><SarthiText role="body" tone="secondary">Four lives in order.</SarthiText><SarthiButton label="Begin" onPress={() => setDraft((value) => ({ ...value, stepId: questions[0]?.id ?? '' }))} />{onSignIn && <SarthiButton label="I have an account" onPress={onSignIn} />}</Card></View></Screen>;
  const answer = draft.answers[question.id]; const next = async () => { if (!isQuestionAnswered(question, answer)) return; if (currentIndex === questions.length - 1) { await store.clear(); await onComplete(draft); return; } const nextDraft = { ...draft, stepId: questions[currentIndex + 1].id }; setDraft(nextDraft); await store.save(nextDraft); };
  const select = (value: string) => { const nextDraft = updateAnswer(draft, question, value); setDraft(nextDraft); void store.save(nextDraft); };
  return <Screen><View style={styles.screen}><Card style={styles.card}><SarthiText role="caption" tone="muted">{question.phase === 'core' ? 'CORE' : 'DETAIL'}</SarthiText><SarthiText role="display">{question.title}</SarthiText>{question.prompt && <SarthiText role="coach" tone="secondary">{question.prompt}</SarthiText>}{question.options ? <View style={styles.options}>{question.options.map((option) => <Pressable key={option.id} accessibilityRole={question.multi ? 'checkbox' : 'radio'} accessibilityState={{ checked: Array.isArray(answer) ? answer.includes(option.id) : answer === option.id }} onPress={() => select(option.id)} style={styles.option}><SarthiText role="caption">{option.label}</SarthiText></Pressable>)}</View> : <TextInput accessibilityLabel={question.title} value={typeof answer === 'string' ? answer : ''} onChangeText={(value) => select(value)} style={styles.input} />}<View style={styles.actions}>{question.phase === 'detail' && <SarthiButton label="Skip" onPress={() => void next()} />}<SarthiButton label={currentIndex === questions.length - 1 ? 'Start Day 1' : 'Continue'} onPress={() => void next()} /></View></Card></View></Screen>;
}
